[package]
name = "reth-clayer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A consensus impl for local testing purposes"

[dependencies]
# reth
reth-beacon-consensus.workspace = true
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-provider.workspace = true
reth-stages.workspace = true
reth-revm.workspace = true
reth-transaction-pool.workspace = true
reth-rpc-types.workspace = true
reth-network = { workspace = true, features = ["serde"] }
reth-db.workspace = true
reth-eth-wire.workspace = true

# async
async-trait.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tokio-stream.workspace = true
tracing.workspace = true    



# engine api
serde_json = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
parking_lot.workspace = true
alloy-primitives = { workspace = true, features = ["rand", "rlp", "serde", "arbitrary"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "stream", "rustls-tls"] }
jsonwebtoken = "8"
url = "2"
zeroize = { version = "1", features = ["zeroize_derive"] }
hex = "0.4"
strum = { version = "0.24", features = ["derive"] }
superstruct = "0.6"
derivative = "2"
serde_derive = "1.0.116"
serde_millis = "0.1"
ethereum_serde_utils = "0.5"
tree_hash = "0.5"
tree_hash_derive = "0.5"
arbitrary = { version = "1", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
auto_impl = "1.0"
lru-cache = "0.1" 

secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }
itertools = { workspace = true }
alloy-rlp = { workspace = true, features = ["derive"] }
reth-ecies = { workspace = true }
reth-tasks.workspace = true
thiserror.workspace = true
config = "0.10.1"
crossbeam-channel = "0.5"

ethers-contract="2.0.14"
ethers-core.workspace = true

[dev-dependencies]
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth.workspace = true
reth-rpc.workspace = true
tempfile.workspace = true
clap.workspace = true
jsonrpsee.workspace = true
eyre.workspace = true
serde_json.workspace = true

[features]
# Included solely to ignore certain tests.
optimism = []
